#!/bin/sh

set -e

git_dir=`git rev-parse --git-dir`

trap 'rm -f "$git_dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$git_dir/$$.tags" --languages="Asm,C,C++"
mv "$git_dir/$$.tags" "$git_dir/tags"

