#!/bin/sh

set -e

dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/tags.$$"' EXIT INT TERM
git ls-files | ctags --tag-relative=yes -L - -f$dir/tags.$$ --languages="Asm,C,C++"
mv $dir/tags.$$ $dir/tags
