(define generic-on-key '("<Super>escape"))
(define generic-on-key? (make-key-predicate '("<Super>escape")))
(define generic-off-key '("<Super>escape"))
(define generic-off-key? (make-key-predicate '("<Super>escape")))
(define generic-begin-conv-key '())
(define generic-begin-conv-key? (make-key-predicate '()))
(define generic-commit-key '("<Control>return"))
(define generic-commit-key? (make-key-predicate '("<Control>return")))
(define generic-cancel-key '("escape"))
(define generic-cancel-key? (make-key-predicate '("escape")))
(define generic-next-candidate-key '())
(define generic-next-candidate-key? (make-key-predicate '()))
(define generic-prev-candidate-key '())
(define generic-prev-candidate-key? (make-key-predicate '()))
(define generic-next-page-key '("next"))
(define generic-next-page-key? (make-key-predicate '("next")))
(define generic-prev-page-key '("prior"))
(define generic-prev-page-key? (make-key-predicate '("prior")))
