(define custom-activate-default-im-name? #t)
(define custom-preserved-default-im-name 'direct)
(define default-im-name 'direct)
(define enabled-im-list '(xtelex))
(define enable-im-switch? #f)
(define switch-im-key '("<IgnoreShift><Control><Alt>\\"))
(define switch-im-key? (make-key-predicate '("<IgnoreShift><Control><Alt>\\")))
(define switch-im-skip-direct-im? #t)
(define enable-im-toggle? #t)
(define toggle-im-key '("<Control> "))
(define toggle-im-key? (make-key-predicate '("<Control> ")))
(define toggle-im-alt-im 'xtelex)
(define uim-color 'uim-color-atok)
(define candidate-window-style 'table)
(define candidate-window-position 'right)
(define enable-lazy-loading? #t)
(define bridge-show-input-state? #f)
(define bridge-show-with? 'time)
(define bridge-show-input-state-time-length 3)
