(define generic-beginning-of-preedit-key '("home"))
(define generic-beginning-of-preedit-key? (make-key-predicate '("home")))
(define generic-end-of-preedit-key '("end"))
(define generic-end-of-preedit-key? (make-key-predicate '("end")))
(define generic-kill-key '())
(define generic-kill-key? (make-key-predicate '()))
(define generic-kill-backward-key '())
(define generic-kill-backward-key? (make-key-predicate '()))
(define generic-backspace-key '("backspace"))
(define generic-backspace-key? (make-key-predicate '("backspace")))
(define generic-delete-key '("delete"))
(define generic-delete-key? (make-key-predicate '("delete")))
(define generic-go-left-key '("left"))
(define generic-go-left-key? (make-key-predicate '("left")))
(define generic-go-right-key '("right"))
(define generic-go-right-key? (make-key-predicate '("right")))
(define generic-return-key '("return"))
(define generic-return-key? (make-key-predicate '("return")))
